// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Troy_Web_Property_Manager.Data;

#nullable disable

namespace Troy_Web_Property_Manager.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260930185846_ReviewQueue")]
    partial class ReviewQueue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Troy_Web_Property_Manager.Models.Applicant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Applicant", (string)null);
                });

            modelBuilder.Entity("Troy_Web_Property_Manager.Models.ApplicantInformation", b =>
                {
                    b.Property<int>("RentalApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("RentalApplicationID");

                    b.Property<string>("CurrentAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RentalApplicationId");

                    b.ToTable("ApplicantInformation", (string)null);
                });

            modelBuilder.Entity("Troy_Web_Property_Manager.Models.ApplicationStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangedByUser")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ChangedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("NewStatus")
                        .HasColumnType("bigint");

                    b.Property<long?>("Outcome")
                        .HasColumnType("bigint");

                    b.Property<long>("PreviousStatus")
                        .HasColumnType("bigint");

                    b.Property<int>("RentalApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("RentalApplicationID");

                    b.HasKey("Id");

                    b.HasIndex("RentalApplicationId");

                    b.ToTable("ApplicationStatusHistory", (string)null);
                });

            modelBuilder.Entity("Troy_Web_Property_Manager.Models.Lease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<int>("RentalApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("RentalApplicationID");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitID");

                    b.HasKey("Id");

                    b.HasIndex("RentalApplicationId");

                    b.HasIndex(new[] { "UnitId", "StartDate", "EndDate" }, "IX_Lease_UnitID_Term");

                    b.ToTable("Lease", null, t =>
                        {
                            t.HasCheckConstraint("CK_Lease_Term", "[EndDate] > [StartDate]");
                        });
                });

            modelBuilder.Entity("Troy_Web_Property_Manager.Models.ManagerNote", b =>
                {
                    b.Property<int>("RentalApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("RentalApplicationID");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("UpdatedByUser")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RentalApplicationId");

                    b.ToTable("ManagerNote", (string)null);
                });

            modelBuilder.Entity("Troy_Web_Property_Manager.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Property", (string)null);
                });

            modelBuilder.Entity("Troy_Web_Property_Manager.Models.RentalApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicantId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicantID");

                    b.Property<bool>("ApplicantInformationSaved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<bool>("ResidenceHistorySaved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReviewClaimed")
                        .HasColumnType("datetime");

                    b.Property<string>("ReviewerUser")
                        .IsConcurrencyToken()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Submitted")
                        .HasColumnType("datetime");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitID");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.HasIndex(new[] { "ApplicantId" }, "IX_RentalApplications_ApplicantID");

                    b.HasIndex(new[] { "ApplicantId", "UnitId" }, "IX_RentalApplications_OpenPerApplicantUnit")
                        .IsUnique()
                        .HasFilter("[Status] IN (1, 2, 3, 7)");

                    b.HasIndex(new[] { "Status", "Submitted" }, "IX_RentalApplications_Status_Submitted");

                    b.ToTable("RentalApplications", null, t =>
                        {
                            t.HasCheckConstraint("CK_RentalApplications_ReviewClaim", "([Status] = 7 AND [ReviewerUser] IS NOT NULL AND [ReviewClaimed] IS NOT NULL) OR ([Status] <> 7 AND [ReviewerUser] IS NULL AND [ReviewClaimed] IS NULL)");
                        });
                });

            modelBuilder.Entity("Troy_Web_Property_Manager.Models.Residence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LandlordName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LandlordPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("MoveInDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("MoveOutDate")
                        .HasColumnType("date");

                    b.Property<int>("RentalApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("RentalApplicationID");

                    b.HasKey("Id");

                    b.HasIndex("RentalApplicationId");

                    b.ToTable("Residence", null, t =>
                        {
                            t.HasCheckConstraint("CK_Residence_Dates", "[MoveOutDate] >= [MoveInDate]");
                        });
                });

            modelBuilder.Entity("Troy_Web_Property_Manager.Models.Status", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Status", (string)null);
                });

            modelBuilder.Entity("Troy_Web_Property_Manager.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int")
                        .HasDefaultValue(1, "DF_Unit_Bedrooms");

                    b.Property<decimal>("MonthlyRent")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m, "DF_Unit_Rent");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UnitTypeId")
                        .HasColumnType("int")
                        .HasColumnName("UnitTypeID");

                    b.HasKey("Id");

                    b.HasIndex("UnitTypeId");

                    b.HasIndex("PropertyId", "UnitNumber")
                        .IsUnique();

                    b.ToTable("Unit", null, t =>
                        {
                            t.HasCheckConstraint("CK_Unit_Bedrooms", "[Bedrooms] >= 0 AND [Bedrooms] <= 10");
                        });
                });

            modelBuilder.Entity("Troy_Web_Property_Manager.Models.UnitType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_UnitType_Active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("UnitType", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Troy_Web_Property_Manager.Models.Applicant", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Applicant_AspNetUsers");
                });

            modelBuilder.Entity("Troy_Web_Property_Manager.Models.ApplicantInformation", b =>
                {
                    b.HasOne("Troy_Web_Property_Manager.Models.RentalApplication", "RentalApplication")
                        .WithOne("ApplicantInformation")
                        .HasForeignKey("Troy_Web_Property_Manager.Models.ApplicantInformation", "RentalApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ApplicantInformation_RentalApplications");

                    b.Navigation("RentalApplication");
                });

            modelBuilder.Entity("Troy_Web_Property_Manager.Models.ApplicationStatusHistory", b =>
                {
                    b.HasOne("Troy_Web_Property_Manager.Models.RentalApplication", "RentalApplication")
                        .WithMany("ApplicationStatusHistories")
                        .HasForeignKey("RentalApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_ApplicationStatusHistory_RentApplications");

                    b.Navigation("RentalApplication");
                });

            modelBuilder.Entity("Troy_Web_Property_Manager.Models.Lease", b =>
                {
                    b.HasOne("Troy_Web_Property_Manager.Models.RentalApplication", "RentalApplication")
                        .WithMany("Leases")
                        .HasForeignKey("RentalApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_Lease_RentApplications");

                    b.HasOne("Troy_Web_Property_Manager.Models.Unit", "Unit")
                        .WithMany("Leases")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("FK_Lease_Unit");

                    b.Navigation("RentalApplication");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Troy_Web_Property_Manager.Models.ManagerNote", b =>
                {
                    b.HasOne("Troy_Web_Property_Manager.Models.RentalApplication", "RentalApplication")
                        .WithOne()
                        .HasForeignKey("Troy_Web_Property_Manager.Models.ManagerNote", "RentalApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ManagerNote_RentalApplications");

                    b.Navigation("RentalApplication");
                });

            modelBuilder.Entity("Troy_Web_Property_Manager.Models.RentalApplication", b =>
                {
                    b.HasOne("Troy_Web_Property_Manager.Models.Applicant", "Applicant")
                        .WithMany("RentalApplications")
                        .HasForeignKey("ApplicantId")
                        .IsRequired()
                        .HasConstraintName("FK_RentApplications_Applicant");

                    b.HasOne("Troy_Web_Property_Manager.Models.Status", "StatusNavigation")
                        .WithMany("RentalApplications")
                        .HasForeignKey("Status")
                        .IsRequired()
                        .HasConstraintName("FK_RentApplications_Status");

                    b.HasOne("Troy_Web_Property_Manager.Models.Unit", "Unit")
                        .WithMany("RentalApplications")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("FK_RentApplications_Unit");

                    b.Navigation("Applicant");

                    b.Navigation("StatusNavigation");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Troy_Web_Property_Manager.Models.Residence", b =>
                {
                    b.HasOne("Troy_Web_Property_Manager.Models.RentalApplication", "RentalApplication")
                        .WithMany("Residences")
                        .HasForeignKey("RentalApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_Residence_RentApplications");

                    b.Navigation("RentalApplication");
                });

            modelBuilder.Entity("Troy_Web_Property_Manager.Models.Unit", b =>
                {
                    b.HasOne("Troy_Web_Property_Manager.Models.Property", "Property")
                        .WithMany("Units")
                        .HasForeignKey("PropertyId")
                        .IsRequired()
                        .HasConstraintName("FK_Unit_Property");

                    b.HasOne("Troy_Web_Property_Manager.Models.UnitType", "UnitType")
                        .WithMany("Units")
                        .HasForeignKey("UnitTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Unit_UnitType");

                    b.Navigation("Property");

                    b.Navigation("UnitType");
                });

            modelBuilder.Entity("Troy_Web_Property_Manager.Models.Applicant", b =>
                {
                    b.Navigation("RentalApplications");
                });

            modelBuilder.Entity("Troy_Web_Property_Manager.Models.Property", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("Troy_Web_Property_Manager.Models.RentalApplication", b =>
                {
                    b.Navigation("ApplicantInformation");

                    b.Navigation("ApplicationStatusHistories");

                    b.Navigation("Leases");

                    b.Navigation("Residences");
                });

            modelBuilder.Entity("Troy_Web_Property_Manager.Models.Status", b =>
                {
                    b.Navigation("RentalApplications");
                });

            modelBuilder.Entity("Troy_Web_Property_Manager.Models.Unit", b =>
                {
                    b.Navigation("Leases");

                    b.Navigation("RentalApplications");
                });

            modelBuilder.Entity("Troy_Web_Property_Manager.Models.UnitType", b =>
                {
                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
