using Bogus;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Troy_Web_Property_Manager.Models;
using Troy_Web_Property_Manager.Rules;

namespace Troy_Web_Property_Manager.Data
{
    /// <summary>
    /// Fills an empty database with realistic demo data generated by Bogus: property managers, applicants,
    /// properties with units, and applications in every status with their history, residences and leases.
    /// The data follows the same rules the app enforces: every history row is an allowed workflow transition,
    /// a unit never has overlapping leases, nothing is submitted while its unit is leased, and an applicant
    /// has at most one open application per unit. A fixed seed makes the data the same on every machine.
    /// </summary>
    public static class DemoDataSeeder
    {
        /// <summary>Password for every demo account.</summary>
        public const string Password = "Demo#2026";

        private const int RandomSeed = 20260930;
        private const int PropertyCount = 6;
        private const int ApplicantCount = 12;
        private const int ApplicationCount = 45;

        /// <summary>Seeds demo data unless the database already has properties. Returns false when it was skipped.</summary>
        public static async Task<bool> SeedAsync(ApplicationDbContext db, UserManager<IdentityUser> userManager)
        {
            if (await db.Properties.AnyAsync()) return false;

            var faker = new Faker("en_US") { Random = new Randomizer(RandomSeed) };

            // UserManager saves through the same context, so the users are part of this transaction too.
            await using var transaction = await db.Database.BeginTransactionAsync();

            var managers = await CreateUsersAsync(userManager, AppRoles.PropertyManager,
                Enumerable.Range(1, 2).Select(i => $"manager{i}@example.com"));
            var applicantUsers = await CreateUsersAsync(userManager, AppRoles.Applicant,
                Enumerable.Range(1, ApplicantCount).Select(i => $"applicant{i}@example.com"));

            var properties = CreateProperties(faker, await db.UnitTypes.ToListAsync());
            var applicants = applicantUsers.Select(user => CreateApplicant(faker, user)).ToList();
            var applications = new ApplicationGenerator(faker, managers, DateTime.Now)
                .Generate(properties.SelectMany(p => p.Units).ToList(), applicants);

            db.Properties.AddRange(properties);
            db.Applicants.AddRange(applicants);
            db.RentalApplications.AddRange(applications);
            await db.SaveChangesAsync();
            await transaction.CommitAsync();
            return true;
        }

        private static async Task<List<IdentityUser>> CreateUsersAsync(UserManager<IdentityUser> userManager, string role, IEnumerable<string> emails)
        {
            var users = new List<IdentityUser>();
            foreach (var email in emails)
            {
                // Reuse an existing account rather than failing, and leave its password alone.
                var user = await userManager.FindByEmailAsync(email);
                if (user is null)
                {
                    user = new IdentityUser { UserName = email, Email = email, EmailConfirmed = true };
                    ThrowIfFailed(await userManager.CreateAsync(user, Password), email);
                }
                if (!await userManager.IsInRoleAsync(user, role))
                {
                    ThrowIfFailed(await userManager.AddToRoleAsync(user, role), email);
                }
                users.Add(user);
            }
            return users;
        }

        private static void ThrowIfFailed(IdentityResult result, string email)
        {
            if (!result.Succeeded)
            {
                throw new InvalidOperationException($"Couldn't seed demo user {email}: {string.Join(" ", result.Errors.Select(e => e.Description))}");
            }
        }

        private static List<Property> CreateProperties(Faker f, List<UnitType> unitTypes)
        {
            var active = unitTypes.Where(t => t.IsActive).ToList();
            var inactive = unitTypes.Where(t => !t.IsActive).ToList();
            string[] suffixes = ["Apartments", "Commons", "Residences", "Terrace", "Court", "Place"];

            return Enumerable.Range(0, PropertyCount).Select(_ =>
            {
                var property = new Property
                {
                    Name = Fit($"{f.Address.StreetName()} {f.PickRandom(suffixes)}"),
                    Address = Fit($"{f.Address.StreetAddress()}, {f.Address.City()}")
                };

                var unitCount = f.Random.Int(4, 10);
                for (var i = 0; i < unitCount; i++)
                {
                    // An occasional unit keeps a retired (inactive) type, which the app allows for existing units.
                    var type = inactive.Count > 0 && f.Random.Bool(0.1f) ? f.PickRandom(inactive) : f.PickRandom(active);
                    var bedrooms = type.Name == "Studio" ? 0 : f.Random.Int(1, 4);
                    property.Units.Add(new Unit
                    {
                        UnitNumber = $"{i / 4 + 1}{i % 4 + 1:00}", // 101, 102, 103, 104, 201, ...
                        Bedrooms = bedrooms,
                        MonthlyRent = Math.Round((900 + bedrooms * 450 + f.Random.Int(-150, 400)) / 25m) * 25,
                        UnitType = type
                    });
                }
                return property;
            }).ToList();
        }

        private static Applicant CreateApplicant(Faker f, IdentityUser user)
        {
            return new()
            {
                UserId = user.Id,
                Name = Fit(f.Name.FullName()),
                Phone = f.Phone.PhoneNumber("(###) ###-####"),
                Email = user.Email!,
                CurrentAddress = Fit($"{f.Address.StreetAddress()}, {f.Address.City()}")
            };
        }

        /// <summary>Keeps generated text within the 50-character columns.</summary>
        private static string Fit(string value)
        {
            return value.Length <= 50 ? value : value[..50].TrimEnd();
        }

        /// <summary>Builds applications with consistent history, sections and leases.</summary>
        private sealed class ApplicationGenerator(Faker f, List<IdentityUser> managers, DateTime now)
        {
            private static readonly ApplicationStatus[][] ApprovedPaths =
            [
                [ApplicationStatus.Draft, ApplicationStatus.Submitted, ApplicationStatus.Approved],
                [ApplicationStatus.Draft, ApplicationStatus.Submitted, ApplicationStatus.Returned, ApplicationStatus.Submitted, ApplicationStatus.Approved]
            ];

            private static readonly ApplicationStatus[][] OtherPaths =
            [
                [ApplicationStatus.Draft],
                [ApplicationStatus.Draft, ApplicationStatus.Withdrawn],
                [ApplicationStatus.Draft, ApplicationStatus.Submitted],
                [ApplicationStatus.Draft, ApplicationStatus.Submitted, ApplicationStatus.Returned, ApplicationStatus.Submitted],
                [ApplicationStatus.Draft, ApplicationStatus.Submitted, ApplicationStatus.Returned],
                [ApplicationStatus.Draft, ApplicationStatus.Submitted, ApplicationStatus.Denied],
                [ApplicationStatus.Draft, ApplicationStatus.Submitted, ApplicationStatus.Withdrawn]
            ];

            private static readonly string[] ReturnComments =
            [
                "Please add your landlord's phone number for your current residence.",
                "We need at least two years of residence history.",
                "The move-in dates don't line up; please check them.",
                "Please confirm your current address."
            ];

            private static readonly string[] DenyComments =
            [
                "Income doesn't meet the requirement for this unit.",
                "We couldn't verify your rental history.",
                "Another applicant was approved for this unit.",
                "Negative landlord reference."
            ];

            private readonly Dictionary<Unit, List<(DateTime Start, DateTime End)>> _leases = [];
            private readonly Dictionary<Unit, List<DateTime>> _submits = [];
            private readonly HashSet<(Applicant, Unit)> _open = [];
            private readonly List<RentalApplication> _applications = [];

            public List<RentalApplication> Generate(List<Unit> units, List<Applicant> applicants)
            {
                // Approvals first, so every later submit can be checked against the leases they create.
                // About a third of the units end up with a lease, some already expired.
                foreach (var unit in f.PickRandom(units, units.Count / 3))
                {
                    TryAdd(f.PickRandom(ApprovedPaths), unit, f.PickRandom(applicants), maxDaysAgo: 700);
                }

                for (var attempts = 0; _applications.Count < ApplicationCount && attempts < ApplicationCount * 20; attempts++)
                {
                    TryAdd(f.PickRandom(OtherPaths), f.PickRandom(units), f.PickRandom(applicants), maxDaysAgo: 240);
                }
                return _applications;
            }

            /// <summary>Adds the application unless its timeline would break a rule; returns whether it was added.</summary>
            private bool TryAdd(ApplicationStatus[] path, Unit unit, Applicant applicant, int maxDaysAgo)
            {
                // Each step happens a few hours to two weeks after the previous one, and all of them in the past.
                var times = new List<DateTime> { now.AddDays(-f.Random.Double(3, maxDaysAgo)) };
                for (var i = 1; i < path.Length; i++)
                {
                    times.Add(times[^1].AddHours(f.Random.Int(4, 24 * 14)));
                }
                if (times[^1] > now) return false;

                var final = path[^1];
                var isOpen = !ApplicationWorkflow.IsTerminal(final);
                if (isOpen && _open.Contains((applicant, unit))) return false;

                var leases = _leases.GetValueOrDefault(unit) ?? [];
                var submits = path.Zip(times).Where(s => s.First == ApplicationStatus.Submitted).Select(s => s.Second).ToList();
                if (submits.Any(t => leases.Any(l => LeasedOn(l, t)))) return false; // the app rejects submitting a leased unit

                (DateTime Start, DateTime End)? lease = null;
                if (final == ApplicationStatus.Approved)
                {
                    var start = times[^1].Date;
                    lease = (start, LeaseRules.EndDateFor(start));
                    var otherSubmits = _submits.GetValueOrDefault(unit) ?? [];
                    if (leases.Any(l => l.Start < lease.Value.End && lease.Value.Start < l.End)) return false; // one lease at a time
                    if (otherSubmits.Any(t => LeasedOn(lease.Value, t))) return false;
                }

                var application = Build(path, times, unit, applicant);
                if (lease is { } l)
                {
                    application.Leases.Add(new Lease { Unit = unit, StartDate = l.Start, EndDate = l.End });
                    Remember(_leases, unit, l);
                }
                foreach (var submit in submits) Remember(_submits, unit, submit);
                if (isOpen) _open.Add((applicant, unit));
                _applications.Add(application);
                return true;
            }

            private static bool LeasedOn((DateTime Start, DateTime End) lease, DateTime time)
            {
                return lease.Start <= time.Date && time.Date < lease.End;
            }

            private static void Remember<T>(Dictionary<Unit, List<T>> byUnit, Unit unit, T value)
            {
                if (!byUnit.TryGetValue(unit, out var list)) byUnit[unit] = list = [];
                list.Add(value);
            }

            private RentalApplication Build(ApplicationStatus[] path, List<DateTime> times, Unit unit, Applicant applicant)
            {
                var application = new RentalApplication
                {
                    Unit = unit,
                    Applicant = applicant,
                    Status = (long)path[^1],
                    Created = times[0],
                    // Set on every submit, so it holds the latest one.
                    Submitted = path.Zip(times)
                        .Where(s => s.First == ApplicationStatus.Submitted)
                        .Select(s => (DateTime?)s.Second)
                        .LastOrDefault()
                };

                // A submitted application has both sections saved; a draft may be at any stage.
                var sectionsDone = path.Contains(ApplicationStatus.Submitted) ? 2 : f.Random.Int(0, 2);
                if (sectionsDone >= 1)
                {
                    application.ApplicantInformation = new ApplicantInformation
                    {
                        Name = applicant.Name,
                        Phone = applicant.Phone,
                        Email = applicant.Email,
                        CurrentAddress = applicant.CurrentAddress
                    };
                    application.ApplicantInformationSaved = true;
                }
                if (sectionsDone >= 2)
                {
                    AddResidences(application, times[0]);
                    application.ResidenceHistorySaved = true;
                }

                for (var i = 0; i < path.Length; i++)
                {
                    var from = i == 0 ? (ApplicationStatus?)null : path[i - 1];
                    var to = path[i];
                    if (from is { } previous && !ApplicationWorkflow.CanTransition(previous, to))
                    {
                        throw new InvalidOperationException($"Demo data path has an invalid transition {previous} -> {to}.");
                    }

                    ReviewOutcome? outcome = to switch
                    {
                        ApplicationStatus.Approved => ReviewOutcome.Approve,
                        ApplicationStatus.Returned => ReviewOutcome.Return,
                        ApplicationStatus.Denied => ReviewOutcome.Deny,
                        _ => null
                    };
                    application.ApplicationStatusHistories.Add(new ApplicationStatusHistory
                    {
                        PreviousStatus = (long?)from ?? 0,
                        NewStatus = (long)to,
                        Outcome = outcome,
                        Comment = outcome switch
                        {
                            ReviewOutcome.Return => f.PickRandom(ReturnComments),
                            ReviewOutcome.Deny => f.PickRandom(DenyComments),
                            ReviewOutcome.Approve => f.Random.Bool(0.3f) ? "Welcome aboard!" : null,
                            _ => null
                        },
                        // Reviews are made by a property manager; every other change by the applicant.
                        ChangedByUser = outcome is null ? applicant.UserId! : f.PickRandom(managers).Id,
                        ChangedDate = times[i]
                    });
                }
                return application;
            }

            /// <summary>One to three prior residences, back to back, ending shortly before the application was started.</summary>
            private void AddResidences(RentalApplication application, DateTime created)
            {
                var moveOut = DateOnly.FromDateTime(created).AddDays(-f.Random.Int(0, 60));
                for (var i = f.Random.Int(1, 3); i > 0; i--)
                {
                    var moveIn = moveOut.AddMonths(-f.Random.Int(6, 48));
                    application.Residences.Add(new Residence
                    {
                        Address = Fit($"{f.Address.StreetAddress()}, {f.Address.City()}"),
                        LandlordName = Fit(f.Name.FullName()),
                        LandlordPhone = f.Phone.PhoneNumber("(###) ###-####"),
                        MoveInDate = moveIn,
                        MoveOutDate = moveOut
                    });
                    moveOut = moveIn.AddDays(-f.Random.Int(0, 30));
                }
            }
        }
    }
}
